import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Line from "../components/line/line";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";

// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900", // Range of font weights
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900", // Range of font weights
});

// Metadata for the app
export const metadata: Metadata = {
  title: "Exclusive | Unleash Your Style",
  description: "Generated by create next app",
};

// RootLayout function with props
export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // Define children prop type
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Line />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
